version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
  AfterInstall:
    - location: after_install.sh
      timeout: 300
 #   - location: zap.sh
  #    timeout: 1800

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
