version: 0.2
phases:
  install:
    commands:
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
      - dpkg -i trivy_0.18.3_Linux-64bit.deb
  build:
    commands:
      - pip install --upgrade awscli
      - aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION > docker_login.sh
      - chmod +x docker_login.sh
      - ./docker_login.sh

      - docker pull 373746118720.dkr.ecr.ap-south-1.amazonaws.com/owaspjuiceshoprepo:latest
      - trivy --exit-code 1 --severity HIGH,MEDIUM --no-progress 373746118720.dkr.ecr.ap-south-1.amazonaws.com/owaspjuiceshoprepo:latest
